### ISSUE TITLE
README download link wrong?

### ISSUE THREAD

**Issue by Silex** [reyzzz/quasaScale-backend#4]
Hello,

The README advices to download wget https://github.com/reyzzz/quasaScale-backend/releases/download/v0.23.0-beta.2/quasascale-backend.zip

But in this file there's only `index.ts` and `.env` and the service, no `bun.lockb` or `package.json`.

That looks wrong.

**Comment by reyzzz** [comment]
Hello Silex,

The files that you found in the zip are correct.
If you only follow the steps in the readme you should have a running quasascale backend.
Let me know if it is not the case.

**Comment by Silex** [comment]
Oh, ok, will try and report.

I assumed you needed the `nodes_modules` directory, but I guess that means everything is included in the `index.ts` file.
